/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netbeansex;

import java.awt.FileDialog;
import java.awt.Frame;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author aluno
 */
public class CadCliente extends javax.swing.JInternalFrame {
    
     ListModel lm;
     int linha;
     private DefaultListModel dfl;
     private Dados d;
    /**
     * Creates new form CadCliente
     */
    public CadCliente() {
        
        initComponents();
        this.lm = lista_dependentes.getModel();
        this.linha=0;
        dfl = new DefaultListModel();
        d = new Dados();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cpf = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        end = new javax.swing.JTextField();
        foto = new javax.swing.JButton();
        cadastrar = new javax.swing.JButton();
        consultar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_dependentes = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        add_dependente = new javax.swing.JTextField();
        add_dependent = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        atualizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista_livros = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Controle de Elfos");

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("CPF");

        jLabel3.setText("Telefone");

        cpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cpfKeyPressed(evt);
            }
        });

        tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telKeyPressed(evt);
            }
        });

        jLabel4.setText("Endereço");

        foto.setText("Foto");
        foto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fotoMouseClicked(evt);
            }
        });

        cadastrar.setText("CADASTRAR");
        cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarMouseClicked(evt);
            }
        });

        consultar.setText("Consultar Elfos");
        consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultarMouseClicked(evt);
            }
        });

        jLabel5.setText("Hobbits");

        jScrollPane1.setViewportView(lista_dependentes);

        jLabel6.setText("Adicionar Hobbits");

        add_dependent.setText("V");
        add_dependent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_dependentMouseClicked(evt);
            }
        });
        add_dependent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_dependentActionPerformed(evt);
            }
        });

        excluir.setText("Excluir Elfo");
        excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluirMouseClicked(evt);
            }
        });

        atualizar.setText("Atualizar Elfo");
        atualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atualizarMouseClicked(evt);
            }
        });

        jButton1.setText("Excluir Hobbit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lista_livros);

        jLabel7.setText("Livros Locados:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(add_dependente, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(add_dependent)
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel4))
                                        .addGap(55, 55, 55)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cpf, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(consultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(atualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(add_dependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(add_dependent))
                                    .addGap(23, 23, 23)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrar)
                    .addComponent(excluir)
                    .addComponent(consultar)
                    .addComponent(atualizar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarMouseClicked
       
       boolean foi1 = false;
       boolean foi2 = false;
       d.conecta("143.106.241.1","3infd1", "3infd1", "3infd1");
       if((nome.getText().trim().equals(""))||(cpf.getText()=="")||(end.getText()=="")||(tel.getText()==""))
            {
               JOptionPane.showConfirmDialog(null,"Não saia da mesa sem pagar a todos","Erro  ( ͠° ͟ʖ ͡°) ",JOptionPane.PLAIN_MESSAGE);
               if((foto.getText()=="Foto")||(foto.getText().trim().equals("nullnull")))
               {
                  JOptionPane.showConfirmDialog(null,"Adicione uma foto!!!\n Para adicionar clique em 'Foto' ","Argh  ( ͠° ͟ʖ ͡°) ",JOptionPane.PLAIN_MESSAGE);
               }
            }
       else{
       foi1 = d.insere_cliente("Cliente_Login",cpf.getText().toString(),nome.getText().toString(),tel.getText().toString(),end.getText().toString(),foto.getText().toString());
       for(int i =0;i<lista_dependentes.getModel().getSize();i++)
       {
        foi2 = d.insere_dependentes("Dependentes_Clientes",cpf.getText(),lista_dependentes.getModel().getElementAt(i));
       }
       if((foi1==true)&&(foi2==true))
       {
           JOptionPane.showConfirmDialog(null,"Elfo alistado para guerra :D","Sucesso",JOptionPane.PLAIN_MESSAGE);
           dfl = new DefaultListModel();
            limpar();
       }
       else if((foi1==false)||(foi2==false))
       {
           JOptionPane.showConfirmDialog(null,"Erro :(","Sauron tá vendo a sua zueira",JOptionPane.PLAIN_MESSAGE);
       }
  
      
       }
       
    }//GEN-LAST:event_cadastrarMouseClicked

    public void limpar()
    {
        try
        {
        cpf.setText("");
        nome.setText("");
        end.setText("");
        tel.setText("");
        foto.setText("Foto");
        add_dependente.setText("");
        DefaultListModel clear = (DefaultListModel)lista_dependentes.getModel();
        clear.removeAllElements();
        foto.setIcon(null);  
        }catch(Exception e){}
    }
    
    private void fotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fotoMouseClicked
     FileDialog fileDialog=new FileDialog((Frame)null);
     fileDialog.setVisible(true);
     foto.setText(fileDialog.getDirectory()+fileDialog.getFile());
     carregaImagem(foto,fileDialog.getDirectory()+fileDialog.getFile());
    }//GEN-LAST:event_fotoMouseClicked

    private void cpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpfKeyPressed
     if(cpf.getText().length()>11)
     {
         cpf.setText(cpf.getText().substring(0,cpf.getText().length()-1));
     }
    }//GEN-LAST:event_cpfKeyPressed

    private void telKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telKeyPressed
       if(tel.getText().length()>11)
     {
         tel.setText(tel.getText().substring(0,tel.getText().length()-1));
     }
    }//GEN-LAST:event_telKeyPressed

    private void consultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarMouseClicked
       limpar();
       String str=JOptionPane.showInputDialog(null,"Digite o nome ou CPF do elfo:","Oráculo",JOptionPane.PLAIN_MESSAGE);
       System.out.println(str);
       d.conecta("143.106.241.1","3infd1", "3infd1", "3infd1");
       ResultSet rs=null;
       try
       {
       Integer.valueOf(str);
           rs=d.consulta("SELECT * FROM Cliente_Login WHERE CPF='"+str+"'");
       }catch(Exception e)
       {
           rs=d.consulta("SELECT * FROM Cliente_Login WHERE Nome='"+str+"'");
       }       
       
       
       try
       {
           rs.next();
       cpf.setText(rs.getString("CPF"));
       nome.setText(rs.getString("Nome"));
       tel.setText(rs.getString("Telefone"));
       end.setText(rs.getString("Endereco"));
       carregaImagem(foto,rs.getString("Foto"));
       foto.setText(rs.getString("Foto"));
       }catch(Exception e)
            {
           JOptionPane.showConfirmDialog(null,"Não temos esse elfo :/","Oráculo",JOptionPane.PLAIN_MESSAGE);
            }
       try
       {
       rs=d.consulta("SELECT Nome FROM Dependentes_Clientes WHERE cpf_cliente='"+cpf.getText().toString().trim()+"'");
       
       while(rs.next())
       {
           dfl.addElement(rs.getString("Nome"));
           
       }
       
       lista_dependentes.setModel(dfl);
       }catch(Exception e)
       {
       }
       d.Kill();
    }//GEN-LAST:event_consultarMouseClicked

    private void add_dependentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_dependentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_dependentActionPerformed

    private void add_dependentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_dependentMouseClicked
        //DefaultListModel dfl = (DefaultListModel)lista_dependentes.getModel();
        dfl.addElement(add_dependente.getText());
        lista_dependentes.setModel(dfl);
        dfl = (DefaultListModel)lista_dependentes.getModel();
        add_dependente.setText("");
    }//GEN-LAST:event_add_dependentMouseClicked

    private void excluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirMouseClicked
        d.conecta("143.106.241.1","3infd1", "3infd1", "3infd1");
        boolean foi2=false;
        String chave = JOptionPane.showInputDialog(null,"Para usar a atualização de elfos você precisa usar antes a consulta.\n Caso já tenha realizado a consulta digite (mellon)","Atualizar instruções",JOptionPane.PLAIN_MESSAGE);
        if(chave.equals("mellon"))
        {
        
        if(d.excluir("Cliente_Login", "Nome",nome.getText()))
        {
            for(int i =0;i<lista_dependentes.getModel().getSize();i++)
                {
                 foi2 = d.excluir("Dependentes_Clientes","cpf_cliente",cpf.getText());
                }
            
           if(foi2==true) JOptionPane.showConfirmDialog(null,"Elfo excluído com sucesso!","Oráculo",JOptionPane.PLAIN_MESSAGE);
           limpar();
            
        }else
        {
         JOptionPane.showConfirmDialog(null,"Erro :/","Oráculo",JOptionPane.PLAIN_MESSAGE);
        
        }
        }
        
    }//GEN-LAST:event_excluirMouseClicked

    private void atualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizarMouseClicked
        d.conecta("143.106.241.1","3infd1", "3infd1", "3infd1");
        boolean foi1=false,foi2=false;
        String chave = JOptionPane.showInputDialog(null,"Para usar a atualização de elfos você precisa usar antes a consulta.\n Caso já tenha realizado a consulta digite (mellon)","Atualizar instruções",JOptionPane.PLAIN_MESSAGE);
        if(chave.equals("mellon"))
        {
          if((d.excluir("Cliente_Login","Nome", nome.getText()))&&(d.excluir("Dependentes_Clientes","cpf_cliente",cpf.getText())))
          {
              foi1 = d.insere_cliente("Cliente_Login",cpf.getText().toString(),nome.getText().toString(),tel.getText().toString(),end.getText().toString(),foto.getText().toString());
                for(int i =0;i<lista_dependentes.getModel().getSize();i++)
                {
                 foi2 = d.insere_dependentes("Dependentes_Clientes",cpf.getText(),lista_dependentes.getModel().getElementAt(i));
                }
                if((foi1==true)&&(foi2==true))
                {
                    JOptionPane.showConfirmDialog(null,"Elfo alistado para guerra :D","Sucesso",JOptionPane.PLAIN_MESSAGE);
                    dfl = new DefaultListModel();
                }
                else
                {
                    JOptionPane.showConfirmDialog(null,"Sauron tá vendo a sua zueira","Erro :(",JOptionPane.PLAIN_MESSAGE);
                }
  
            limpar();
          }
          
        }
        else
        {
          consultarMouseClicked(evt);
        }
        
        
        
    }//GEN-LAST:event_atualizarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       DefaultListModel dlm =(DefaultListModel) lista_dependentes.getModel();
       dlm.remove(lista_dependentes.getSelectedIndex());
       lista_dependentes.setModel(dlm);       
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_dependent;
    private javax.swing.JTextField add_dependente;
    private javax.swing.JButton atualizar;
    private javax.swing.JButton cadastrar;
    private javax.swing.JButton consultar;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField end;
    private javax.swing.JButton excluir;
    private javax.swing.JButton foto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lista_dependentes;
    private javax.swing.JList<String> lista_livros;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables

    private void carregaImagem(JButton botao, String arquivo) 
    {
       try{
        File file =new File(arquivo);
        BufferedImage bufi= ImageIO.read(file);
        ImageIcon ico=new ImageIcon(bufi);
        
        Image img = ico.getImage() ;  
        Image newimg = img.getScaledInstance(foto.getWidth(),foto.getHeight(),  java.awt.Image.SCALE_SMOOTH ) ;  
        ico = new ImageIcon( newimg );
        botao.setIcon(ico);
        
        //BIANCA QND ESTUDAR IGNORE ISSO
       // botao.setIcon(new ImageIcon(ImageIO.read(getClass().getResource(arquivo))));
       
        }catch(Exception e)
            {
                System.out.println("ERRO:"+e.toString());
            }
    }
}
