/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netbeansex;

import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class CadLivro extends javax.swing.JInternalFrame {
     private Dados d;
    /**
     * Creates new form Livros
     */
    public CadLivro() {
        initComponents();
        d=new Dados();
     
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        autor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        editora = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        qntd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cadastrar = new javax.swing.JButton();
        atualizar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        data = new javax.swing.JFormattedTextField();
        try{
            javax.swing.text.MaskFormatter dataf= new javax.swing.text.MaskFormatter("####-##-##");
            data = new javax.swing.JFormattedTextField(dataf);
        }
        catch (Exception e){
        }
        consultar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Pergaminhos Arcanos");
        setToolTipText("");

        jLabel1.setText("ID");

        jLabel2.setText("Título");

        autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorActionPerformed(evt);
            }
        });

        jLabel3.setText("Autor");

        jLabel4.setText("Editora");

        jLabel5.setText("Data");

        jLabel6.setText("Qntd");

        cadastrar.setText("CADASTRAR");
        cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarMouseClicked(evt);
            }
        });

        atualizar.setText("Atualizar");
        atualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atualizarMouseClicked(evt);
            }
        });
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });

        excluir.setText("Excluir");
        excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluirMouseClicked(evt);
            }
        });

        consultar.setText("Consultar");
        consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(titulo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editora, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(autor, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(qntd, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(data))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(qntd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrar)
                    .addComponent(atualizar)
                    .addComponent(excluir)
                    .addComponent(consultar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autorActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atualizarActionPerformed

    private void cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarMouseClicked
      d.conecta("143.106.241.1","3infd1", "3infd1", "3infd1");
      boolean camposOK=true;
      boolean foi = false;
      
      if((id.getText().equals(""))||(titulo.getText().equals(""))||(autor.getText().equals(""))||(editora.getText().equals(""))||(data.getText().equals(""))||(qntd.getText().equals("")))
      {
      JOptionPane.showConfirmDialog(null,"Preencha todos os campos","Erro  ( ͠° ͟ʖ ͡°) ",JOptionPane.PLAIN_MESSAGE);
      camposOK=false;
      }
      try
      {
         Integer.valueOf(qntd.getText().toString());
       //  Integer.valueOf(data.getText().toString());
         
      }catch(Exception e)
      {
          e.printStackTrace();
          camposOK=false;
      }
      
      if(camposOK==true)
      {
      String dispon=""+1;
      foi=d.insere_livro("Livros",id.getText().toString(),titulo.getText().toString(),autor.getText().toString(),editora.getText().toString(),qntd.getText().toString(),data.getText().toString(),dispon);
             
      if(foi==true)
        {
        JOptionPane.showConfirmDialog(null,"Pergaminho cadastrado :D","Sucesso",JOptionPane.PLAIN_MESSAGE);
        limpar();
        }
      
      if((foi==false))
      {
       JOptionPane.showConfirmDialog(null,"Erro :(","Sauron tá vendo a sua zueira",JOptionPane.PLAIN_MESSAGE);
      }
      }      
    }//GEN-LAST:event_cadastrarMouseClicked

    private void limpar()
    {
     id.setText("");
     titulo.setText("");
     autor.setText("");
     editora.setText("");
     data.setText("");
     qntd.setText("");     
    }
    
    private void atualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizarMouseClicked
       d.conecta("143.106.241.1","3infd1", "3infd1", "3infd1");
        String chave = JOptionPane.showInputDialog(null,"Para usar a atualização de elfos você precisa usar antes a consulta.\n Caso já tenha realizado a consulta e alterado os dados desejados, digite (mellon)","Atualizar instruções",JOptionPane.PLAIN_MESSAGE);
        if(chave.equals("mellon"))
        {
          if(d.excluir("Livros","id_livro", id.getText()))
          {
             cadastrarMouseClicked(evt);
          }else{
          JOptionPane.showInputDialog(null,"Erro :(","Oráculo",JOptionPane.PLAIN_MESSAGE);
          }
          
        }
        else
        {          
          consultarMouseClicked(evt);
        }
      
    }//GEN-LAST:event_atualizarMouseClicked

    private void consultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarMouseClicked
       limpar();
        String str=JOptionPane.showInputDialog(null,"Digite o nome ou ID do livro:","Oráculo",JOptionPane.PLAIN_MESSAGE);    
       d.conecta("143.106.241.1","3infd1", "3infd1", "3infd1");
       ResultSet rs= null;
       
       
       try{
        Integer.valueOf(str);
        rs=d.consulta("SELECT * FROM Livros WHERE id_livro='"+str+"'");
       }catch(Exception e)
       {
       rs=d.consulta("SELECT * FROM Livros WHERE Titulo_livro='"+str+"'");
       }
       
       try
       {
       rs.next();
       id.setText(rs.getString("id_livro"));
       titulo.setText(rs.getString("Titulo_livro"));
       autor.setText(rs.getString("Autor"));
       editora.setText(rs.getString("Editora"));
       qntd.setText(rs.getString("Qntd"));
       data.setText(rs.getString("Data"));    
       
       }catch(Exception e)
            {
              JOptionPane.showConfirmDialog(null,"Não temos esse livro :/","Oráculo",JOptionPane.PLAIN_MESSAGE);
            }
       
    }//GEN-LAST:event_consultarMouseClicked

    private void excluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirMouseClicked
       String str=JOptionPane.showInputDialog(null,"Digite o nome do livro:","Oráculo",JOptionPane.PLAIN_MESSAGE);    
       d.conecta("143.106.241.1","3infd1", "3infd1", "3infd1");
       ResultSet rs=d.consulta("SELECT * FROM Livros WHERE Titulo_livro='"+str+"'");
        try
       {
       rs.next();
       String str_id=(rs.getString("id_livro"));
       String str_titulo=(rs.getString("Titulo_livro"));
       String str_autor=(rs.getString("Autor"));
       String str_editora=(rs.getString("Editora"));
       String str_qntd=(rs.getString("Qntd"));
       String str_data=(rs.getString("Data"));       
       
       d.excluir("Livros","Titulo_livro", str);
       String dispon=""+0;
       d.insere_livro("Livros",str_id,str_titulo,str_autor,str_editora,str_qntd,str_data,dispon);
       
       }catch(Exception e)
            {
              JOptionPane.showConfirmDialog(null,"Não temos esse livro :/","Oráculo",JOptionPane.PLAIN_MESSAGE);
            }
       
       
    }//GEN-LAST:event_excluirMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizar;
    private javax.swing.JTextField autor;
    private javax.swing.JButton cadastrar;
    private javax.swing.JButton consultar;
    private javax.swing.JFormattedTextField data;
    private javax.swing.JTextField editora;
    private javax.swing.JButton excluir;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField qntd;
    private javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables
}
