/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netbeansex;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author olivato
 */
public class Controle extends javax.swing.JInternalFrame {

    Dados d = new Dados();
    public Controle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Controle");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Livro", "Status"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        jButton1.setText("DESALOCAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("ATUALIZAR");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        
       
    }//GEN-LAST:event_jButton2MouseClicked

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        d.conecta("143.106.241.1","3infd1", "3infd1", "3infd1");
        DefaultTableModel dfm = (DefaultTableModel)tabela.getModel();
        int linha=0;
        boolean controle=true;
        ResultSet rs = d.consulta("SELECT \n" +
        "Nome\n" +
        "FROM \n" +
        "Funcionario_Login\n" +
        "INNER JOIN Livros_Locados ON Funcionario_Login.CPF = Livros_Locados.CPF_cliente \n" +
        "UNION ALL\n" +
        "SELECT\n" +
        "Nome\n" +
        "FROM \n" +
        "Cliente_Login\n" +
        "INNER JOIN Livros_Locados ON Cliente_Login.CPF = Livros_Locados.CPF_cliente");
        
        ResultSet rss = d.consulta("SELECT\n" +
        "Titulo_livro\n" +
        "FROM \n" +
        "Livros\n" +
        "INNER JOIN Livros_Locados ON Livros.id_livro= Livros_Locados.id_livro");
        
        ResultSet rsss = d.consulta("SELECT Data_locacao FROM Livros_Locados");
        try {
            while(rs.next())
            {
                dfm.addRow(new String[dfm.getColumnCount()]);
                dfm.setValueAt(rs.getString("Nome"),linha,0);
                linha++;
            }
            linha=0;
            while(rss.next())
            {
                dfm.setValueAt(rss.getString("Titulo_livro"),linha,1);
                linha++;
            }
            linha=0;
            while(rsss.next())
            {   
                Calendar c = Calendar.getInstance(); 
                Date date = rsss.getDate("Data_locacao");
                Date atual = new Date();
                c.setTime(date); 
                c.add(Calendar.DATE, 7);
                date = c.getTime();
                if(atual.after(date))
                {
                    dfm.setValueAt("NAO",linha,2);
                }
                else
                {
                    dfm.setValueAt("OK",linha,2);
                }
                linha++;
                
                
            }
        } catch (SQLException ex) {
            //Logger.getLogger(Controle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameActivated

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try
        {
            ResultSet rs = null;
            String cpf=null;
            int row=tabela.getSelectedRow();
            String nome=(String) tabela.getValueAt(row, 0);
            String livro=(String) tabela.getValueAt(row, 1);
            System.out.println(nome);
            System.out.println(livro);
            rs=d.consulta("SELECT CPF From Cliente_Login where Nome='"+nome+"';");
            if(rs.next())
            {
                cpf=rs.getString("CPF");
            }
            rs=d.consulta("SELECT cpf_cliente From Dependentes_Clientes where Nome='"+nome+"';");
            if(rs.next())
            {
                cpf=rs.getString("cpf_cliente");
            }
            rs=d.consulta("SELECT CPF From Funcionario_Login where Nome='"+nome+"';");
            if(rs.next())
            {
                cpf=rs.getString("CPF");
            }
            rs=d.consulta("SELECT id_livro FROM Livros where Titulo_livro='"+livro+"';");
            rs.next();
            livro=rs.getString("id_livro");
            System.out.println(cpf);
            System.out.println(livro);
            d.excluirFocado(cpf, livro);
            
        }catch(Exception e)
        {
            System.out.println("ERRO");
        }
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
