/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netbeansex;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno
 */
public class LocacaoLivros extends javax.swing.JInternalFrame {
    
    Dados d = new Dados();
    String tipo;
    /**
     * Creates new form LocacaoLivros
     */
    public LocacaoLivros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        livro = new javax.swing.JTextField();
        nomes = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        livronome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomenome = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Locação de Pergaminhos");
        setToolTipText("");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Autor", "Qntd."
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        livro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                livroFocusGained(evt);
            }
        });
        livro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                livroKeyReleased(evt);
            }
        });

        nomes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomesFocusGained(evt);
            }
        });
        nomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomesActionPerformed(evt);
            }
        });
        nomes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomesKeyReleased(evt);
            }
        });

        jButton1.setText("Locar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        livronome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        livronome.setText("Livro");

        jLabel2.setText("Locar Para");

        nomenome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nomenome.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(livro, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addComponent(livronome, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomenome, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomes, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(livronome)
                    .addComponent(nomenome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(livro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomesActionPerformed

    private void livroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_livroKeyReleased
        Xoxo();
    }//GEN-LAST:event_livroKeyReleased

    private void nomesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomesKeyReleased
        Gogo();
    }//GEN-LAST:event_nomesKeyReleased

    private void nomesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomesFocusGained
        Gogo();
    }//GEN-LAST:event_nomesFocusGained

    private void livroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_livroFocusGained
        Xoxo();
    }//GEN-LAST:event_livroFocusGained

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        
        if(tabela.getModel().getColumnName(1).equals("Autor"))
        {
            livronome.setText((String)tabela.getValueAt(tabela.getSelectedRow(), 0));
        }
        else
        {
            nomenome.setText((String)tabela.getValueAt(tabela.getSelectedRow(), 0));
            tipo=(String)tabela.getValueAt(tabela.getSelectedRow(), 1);
            
        }
        
        
    }//GEN-LAST:event_tabelaMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        ResultSet rs;
        String idLivro=null;
        String cpf=null;
        try
        {
        rs = d.consulta("SELECT id_livro FROM Livros where Titulo_livro='"+livronome.getText()+"';");
        rs.next();
        idLivro = rs.getString("id_livro");         
            if(tipo.equals("Anão"))
            {
                rs = d.consulta("SELECT CPF FROM Funcionario_Login where Nome='"+nomenome.getText()+"';");
                rs.next();
                cpf=rs.getString("CPF");

            }
            if(tipo.equals("Elfa"))
            {
                rs = d.consulta("SELECT CPF FROM Cliente_Login where Nome='"+nomenome.getText()+"';");
                rs.next();
                cpf=rs.getString("CPF");

            }
            if(tipo.equals("Dependentes"))
            {
                rs = d.consulta("SELECT cpf_cliente FROM Dependentes_Clientes where Nome='"+nomenome.getText()+"';");
                rs.next();
                cpf=rs.getString("cpf_cliente");

            }
        
        //ver se a pessoa já pegou esse livro
        rs=d.consulta("SELECT id_livro FROM Livros_Locados where CPF_cliente='"+cpf+"'");
        int controle=0;
        while((rs.next())&&(controle!=3))
        {
            if(idLivro.equals(rs.getString("id_livro")))
            {
                  System.out.println("CAIU");
                  controle=3;  
            }
            else
            {
                controle++;
            }
        }
        if((controle<3))
        {
         d.insere_locacao(idLivro,cpf);
         JOptionPane.showMessageDialog(null,"Livro locado!");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Erro, esse livro já está locado para essa pessoa ou já fez a locação de 3 livros!");
        }
          
            
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Ih, deu errro!");
        }
        
       
       
    }//GEN-LAST:event_jButton1MouseClicked
    public void Xoxo()
    {
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Autor", "Qntd."
            }
        ));
     d.conecta("143.106.241.1","3infd1", "3infd1", "3infd1");
     ResultSet rs=null;
     DefaultTableModel dfm = (DefaultTableModel)tabela.getModel();
     dfm.setColumnCount(3);
     dfm.setRowCount(0);
     
       try
       {
           rs=d.consulta("SELECT Titulo_livro,Autor,Qntd FROM Livros WHERE Titulo_livro LIKE '%"+livro.getText()+"%';");
       }catch(Exception e)
       {
           e.printStackTrace();
       }
        try {
            int linha =0;
            while(rs.next())
            {   
                dfm.addRow(new String[dfm.getColumnCount()]);
                dfm.setValueAt(rs.getString("Titulo_livro"),linha,0);
                dfm.setValueAt(rs.getString("Autor"),linha,1);
                dfm.setValueAt(rs.getString("Qntd"),linha,2);
                linha++;
            }
            tabela.setModel(dfm);
        } catch (Exception ex) {
           ex.printStackTrace();
        }
    }
    public void Gogo()
    {
         tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Tipo"
            }
        ));
     d.conecta("143.106.241.1","3infd1", "3infd1", "3infd1");
     ResultSet rs=null;
     DefaultTableModel dfm = (DefaultTableModel)tabela.getModel();
     dfm.setColumnCount(2);
     dfm.setRowCount(0);
     int linha =0;
       try
       {
           rs=d.consulta("SELECT Nome FROM Cliente_Login WHERE Nome LIKE '%"+nomes.getText()+"%';");
       }catch(Exception e)
       {
           e.printStackTrace();
       }
        try {
            
            while(rs.next())
            {   
                dfm.addRow(new String[dfm.getColumnCount()]);
                dfm.setValueAt(rs.getString("Nome"),linha,0);
                dfm.setValueAt("Elfa", linha, 1);
                linha++;
            }
            rs=null;
            
        } catch (Exception ex) {
           ex.printStackTrace();
        }
       
        try
       {
           rs=d.consulta("SELECT Nome FROM Dependentes_Clientes WHERE Nome LIKE '%"+nomes.getText()+"%';");
       }catch(Exception e)
       {
           e.printStackTrace();
       }
        try {
            
            while(rs.next())
            {   
                dfm.addRow(new String[dfm.getColumnCount()]);
                dfm.setValueAt(rs.getString("Nome"),linha,0);
                dfm.setValueAt("Dependentes", linha, 1);
                linha++;
            }
            rs=null;
        } catch (Exception ex) {
           ex.printStackTrace();
        }
        try
       {
           rs=d.consulta("SELECT Nome FROM Funcionario_Login WHERE Nome LIKE '%"+nomes.getText()+"%';");
       }catch(Exception e)
       {
           e.printStackTrace();
       }
        try {
            
            while(rs.next())
            {   
                dfm.addRow(new String[dfm.getColumnCount()]);
                dfm.setValueAt(rs.getString("Nome"),linha,0);
                dfm.setValueAt("Anão", linha, 1);
                linha++;
            }
            rs=null;
            tabela.setModel(dfm);
        } catch (Exception ex) {
           ex.printStackTrace();
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField livro;
    private javax.swing.JLabel livronome;
    private javax.swing.JLabel nomenome;
    private javax.swing.JTextField nomes;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
